package com.example.warehouseapplication


import jakarta.persistence.*
import org.springframework.data.annotation.CreatedDate
import org.springframework.data.annotation.LastModifiedDate
import org.springframework.data.jpa.domain.support.AuditingEntityListener
import java.math.BigDecimal
import java.time.Instant
import java.time.LocalDate


@MappedSuperclass
@EntityListeners(AuditingEntityListener::class)
open class BaseEntity(

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    open val id: Long? = null,

    @CreatedDate
    @Column(nullable = false, updatable = false)
    open var createdAt: Instant? = null,

    @LastModifiedDate
    @Column(nullable = false)
    open var updatedAt: Instant? = null,

    @Column(nullable = false)
    open var active: Boolean = true
)


@Entity
@Table(name = "warehouses")
open class Warehouse(

    @Column(nullable = false)
    var name: String

) : BaseEntity()


@Entity
@Table(name = "workers")
open class Worker(

    @Column(nullable = false)
    var firstName: String,

    @Column(nullable = false)
    var lastName: String,

    @Column(nullable = false)
    var phone: String,

    @Column(nullable = false, unique = true)
    var employeeCode: String,

    @Column(nullable = false)
    var passwordHash: String,

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "warehouse_id", nullable = false)
    var warehouse: Warehouse

) : BaseEntity()

@Entity
@Table(name = "categories")
open class Category(

    @Column(nullable = false)
    var name: String,

    // Ichma-ich kategoriya (self reference)
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "parent_id")
    var parent: Category? = null

) : BaseEntity()


@Entity
@Table(name = "units")
open class UnitOfMeasure(

    @Column(nullable = false)
    var name: String

) : BaseEntity()

@Entity
@Table(name = "currencies")
open class Currency(

    @Column(nullable = false)
    var name: String

) : BaseEntity()

@Entity
@Table(name = "suppliers")
open class Supplier(

    @Column(nullable = false)
    var name: String,

    @Column(nullable = false)
    var phone: String

) : BaseEntity()


@Entity
@Table(name = "products")
open class Product(

    @Column(nullable = false)
    var name: String,

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "category_id", nullable = false)
    var category: Category,

    @Column(nullable = false, unique = true)
    var productCode: String,           // generated by system

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "unit_id", nullable = false)
    var unit: UnitOfMeasure,

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "supplier_id", nullable = false)
    var supplier: Supplier

) : BaseEntity() {

    @OneToMany(
        mappedBy = "product",
        cascade = [CascadeType.ALL],
        orphanRemoval = true
    )
    var images: MutableList<ProductImage> = mutableListOf()
}

//Savol bor


@Entity
@Table(name = "product_images")
open class ProductImage(

    @Column(nullable = false)
    var url: String,

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "product_id", nullable = false)
    var product: Product

) : BaseEntity()


@Entity
@Table(name = "stock_entries")
open class StockEntry(

    @Column(nullable = false)
    var date: LocalDate,

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "warehouse_id", nullable = false)
    var warehouse: Warehouse,

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "supplier_id", nullable = false)
    var supplier: Supplier,

    @Column(nullable = false)
    var invoiceNumber: String,

    @Column(nullable = false, unique = true)
    var entryCode: String              // generated by system, unique per entry

) : BaseEntity() {

    @OneToMany(
        mappedBy = "stockEntry",
        cascade = [CascadeType.ALL],
        orphanRemoval = true
    )
    var items: MutableList<StockEntryItem> = mutableListOf()
}

// yana savol bor

@Entity
@Table(name = "stock_entry_items")
open class StockEntryItem(

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "stock_entry_id", nullable = false)
    var stockEntry: StockEntry,

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "product_id", nullable = false)
    var product: Product,

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "unit_id", nullable = false)
    var unit: UnitOfMeasure,

    @Column(nullable = false, precision = 19, scale = 3)
    var quantity: BigDecimal,          // e.g. 30 => 30 kg

    @Column(nullable = false, precision = 19, scale = 2)
    var purchasePrice: BigDecimal,     // kirim narxi

    @Column(nullable = false, precision = 19, scale = 2)
    var salePrice: BigDecimal,         // sotish narxi

    var expiryDate: LocalDate? = null, // yaroqlilik muddati

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "currency_id", nullable = false)
    var currency: Currency

) : BaseEntity()

@Entity
@Table(name = "sales")
open class Sale(

    @Column(nullable = false)
    var date: LocalDate,

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "warehouse_id", nullable = false)
    var warehouse: Warehouse,

    @Column(nullable = false)
    var invoiceNumber: String,

    @Column(nullable = false, unique = true)
    var saleCode: String               // generated by system

) : BaseEntity() {

    @OneToMany(
        mappedBy = "sale",
        cascade = [CascadeType.ALL],
        orphanRemoval = true
    )
    var items: MutableList<SaleItem> = mutableListOf()
}

//Yana savol

@Entity
@Table(name = "sale_items")
open class SaleItem(

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "sale_id", nullable = false)
    var sale: Sale,

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "product_id", nullable = false)
    var product: Product,

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "unit_id", nullable = false)
    var unit: UnitOfMeasure,

    @Column(nullable = false, precision = 19, scale = 3)
    var quantity: BigDecimal,

    @Column(nullable = false, precision = 19, scale = 2)
    var price: BigDecimal,

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "currency_id", nullable = false)
    var currency: Currency

) : BaseEntity()


@Entity
@Table(
    name = "product_stock",
    uniqueConstraints = [
        UniqueConstraint(
            name = "uk_product_stock_warehouse_product",
            columnNames = ["warehouse_id", "product_id"]
        )
    ]
)
open class ProductStock(

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "warehouse_id", nullable = false)
    var warehouse: Warehouse,

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "product_id", nullable = false)
    var product: Product,

    @Column(nullable = false, precision = 19, scale = 3)
    var quantity: BigDecimal = BigDecimal.ZERO

) : BaseEntity()

@Entity
@Table(name = "notification_settings")
open class NotificationSetting(

    @Column(nullable = false, unique = true)
    var key: String,

    @Column(nullable = false)
    var daysBefore: Long

) : BaseEntity()

@Entity
@Table(
    name = "expiry_notifications",
    uniqueConstraints = [
        UniqueConstraint(
            name = "uk_expiry_notification_item_chat",
            columnNames = ["stock_entry_item_id", "chat_id"]
        )
    ]
)
open class ExpiryNotification(

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "stock_entry_item_id", nullable = false)
    var stockEntryItem: StockEntryItem,

    @Column(nullable = false)
    var chatId: String,                // single configured chat for the whole system

    @Column(nullable = false)
    var sentAt: Instant

) : BaseEntity()